import { cleanName,equipOutfit,outfitCost,dailyProgress,exportVillage,importVillage,saveVillage,localDay } from './village-state.js';
import { favoriteThings } from './village-life.js';
export function createVillageTools({data,storage,friends,selected,refresh,persist}){
 const $=id=>document.getElementById(id);
 const profile=document.createElement('div');profile.className='egg-personal';profile.innerHTML='<p id="egg-favorite"></p><p id="egg-activity" aria-live="off"></p><form id="nickname-form"><label for="egg-nickname">우리만의 이름 <small>최대 12글자</small></label><div><input id="egg-nickname" maxlength="24" autocomplete="off" placeholder="별명을 지어 주세요"/><button>이름 저장</button></div></form><details class="egg-wardrobe"><summary>작은 옷장 <span id="egg-fragments"></span></summary><p>같은 달걀을 뽑으면 조각 +1! 조각은 사라지지 않고 장식이 차례로 열려요.</p><div id="outfit-options"></div><small>장식은 능력치를 바꾸지 않아요. 꽃 장식은 마을의 작은 화단도 함께 꾸며요.</small></details><p id="personal-message" role="status"></p>';
 $('resident-stats').after(profile);
 const labels={none:'기본 모습',ribbon:'분홍 리본',hat:'밀짚모자',garden:'꽃 배지 + 작은 화단'};
 for(const [key,cost] of Object.entries(outfitCost)){const b=document.createElement('button');b.type='button';b.dataset.outfit=key;b.textContent=labels[key]+(cost?' · 조각 '+cost:'');b.addEventListener('click',()=>{if(equipOutfit(data,selected(),key)){persist();refresh();$('personal-message').textContent=labels[key]+'으로 갈아입었어요!';}});$('outfit-options').append(b);}
 $('nickname-form').addEventListener('submit',e=>{e.preventDefault();const id=selected();data.nicknames[id]=cleanName($('egg-nickname').value);$('egg-nickname').value=data.nicknames[id];persist();refresh();$('personal-message').textContent=data.nicknames[id]?'이제 '+data.nicknames[id]+'이라고 불러줄게!':'원래 이름으로 불러줄게!';});
 const daily=document.createElement('div');daily.className='daily-card';daily.innerHTML='<strong>오늘도 같이 놀자! <b id="daily-count"></b></strong><p id="daily-copy"></p><div class="daily-stamps" id="daily-stamps" aria-hidden="true"></div><small>승패 상관없이 하루 3판 완료 → 뽑기권 1장<br>끝까지 결과를 보면 인정돼요. 매일 자정에 새로 시작해요.</small>';
 document.querySelector('.ticket-reward').after(daily);
 const backup=document.createElement('section');backup.className='backup-card';backup.innerHTML='<div><h2>우리 마을, 소중히 보관하기</h2><p>저장 파일을 다른 휴대폰이나 컴퓨터에서 불러올 수도 있어요.</p><small>이 브라우저에 자동 저장돼요. 브라우저 데이터를 지우기 전에는 파일로 보관해 주세요.</small></div><div class="backup-actions"><button id="save-export">저장 파일 받기 ↓</button><button id="save-import">저장 파일 불러오기 ↑</button><button id="save-undo" hidden>불러오기 전 마을 복구</button><input id="save-file" type="file" accept=".json,application/json" hidden/></div><p id="backup-message" role="status"></p>';
 document.querySelector('.village-bottom').after(backup);
 backup.querySelector('small').id='backup-storage-note';if(data.recovered)$('backup-message').textContent='최근 정상 저장 기록으로 마을을 복구했어요. 파일로도 보관해 두면 든든해요.';
 const dialog=document.createElement('dialog');dialog.id='backup-dialog';dialog.innerHTML='<h2>이 마을을 불러올까요?</h2><p id="backup-preview"></p><p>현재 마을을 선택한 기록으로 바꿔요. 불러오기 전 마을도 이 브라우저에 한 번 보관해 둘게요.</p><div class="backup-actions"><button id="backup-cancel">취소</button><button id="backup-apply">이 마을 불러오기</button></div>';document.body.append(dialog);
 const conflictDialog=document.createElement('dialog');conflictDialog.id='save-conflict';conflictDialog.className='save-dialog';conflictDialog.innerHTML='<h2>다른 탭에서 마을이 바뀌었어요</h2><p>기록이 서로 덮어쓰이지 않도록 잠시 멈췄어요. 최신 마을을 불러오면 이어서 놀 수 있어요.</p><p>이 탭의 기록도 남기고 싶다면 먼저 파일로 받아 주세요.</p><div class="backup-actions"><button id="conflict-export">이 탭의 기록 파일 받기</button><button id="conflict-reload">최신 마을 불러오기</button></div>';document.body.append(conflictDialog);conflictDialog.addEventListener('cancel',e=>e.preventDefault());$('conflict-reload').addEventListener('click',()=>location.reload());$('conflict-export').addEventListener('click',()=>$('save-export').click());
 let pending=null;
 const showPreview=text=>{pending=importVillage(text);$('backup-preview').textContent='달걀 '+pending.owned.length+'마리 · 별조각 '+pending.shards+'개 · 뽑기권 '+pending.tickets+'장 · '+pending.matches+'경기 / '+pending.wins+'승';dialog.showModal();};
 const report=e=>$('backup-message').textContent=e.message||'파일을 읽지 못했어요. 현재 마을은 그대로예요.';
 try{$('save-undo').hidden=!storage?.getItem('eggy-village-before-import');}catch{}
 $('save-export').addEventListener('click',()=>{const blob=new Blob([exportVillage(data)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='eggy-village-'+localDay()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);$('backup-message').textContent='저장 파일을 만들었어요. 내려받은 파일을 잘 보관해 주세요.';});
 $('save-import').addEventListener('click',()=>$('save-file').click());
 $('save-file').addEventListener('change',async()=>{const file=$('save-file').files[0];$('save-file').value='';if(!file)return;try{if(file.size>250000)throw Error('파일이 너무 커요. 동글동글 저장 파일을 골라주세요.');showPreview(await file.text());}catch(e){report(e);}});
 $('save-undo').addEventListener('click',()=>{try{showPreview(storage.getItem('eggy-village-before-import'));}catch(e){report(e);}});
 $('backup-cancel').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{if(!dialog.open)pending=null;});
 $('backup-apply').addEventListener('click',()=>{if(!pending)return;try{if(!storage)throw Error('브라우저 저장을 사용할 수 없어 불러오지 않았어요.');storage.setItem('eggy-village-before-import',exportVillage(data));if(!saveVillage(storage,pending))throw Error('저장 공간이 부족해요. 현재 마을은 그대로 유지돼요.');location.reload();}catch(e){dialog.close();report(e);}});
 let lastSelected=-1;
 return {refresh(){const id=selected();$('egg-favorite').textContent='좋아하는 것 · '+favoriteThings[id];if(lastSelected!==id)$('egg-nickname').value=data.nicknames[id];if(lastSelected!==id)$('personal-message').textContent='';lastSelected=id;
  $('egg-fragments').textContent='조각 '+data.fragments[id]+'개';document.querySelectorAll('[data-outfit]').forEach(b=>{b.disabled=data.fragments[id]<outfitCost[b.dataset.outfit];b.setAttribute('aria-pressed',String(data.outfits[id]===b.dataset.outfit));});
  const d=dailyProgress(data);$('daily-count').textContent=d.completed+' / 3';$('daily-copy').textContent=d.claimed?'오늘의 뽑기권 1장을 받았어요 ✓':'뽑기권까지 '+(3-d.completed)+'판! 져도 괜찮아요.';$('daily-stamps').textContent=Array.from({length:3},(_,i)=>i<d.completed?'●':'○').join('   ');
 },activity(text){$('egg-activity').textContent=text;},saveStatus(saved){$('backup-storage-note').textContent=saved?'이 브라우저에 자동 저장돼요. 브라우저 데이터를 지우기 전에는 파일로 보관해 주세요.':'지금은 브라우저에 저장하지 못했어요. 방문을 끝내기 전에 저장 파일을 받아 주세요.';},conflict(){if(!conflictDialog.open)conflictDialog.showModal();}};
}
