import './welcome.css';
export function createWelcome({data,onBattle,onExplore,onCollection}){
 const key='eggy-welcome-v1',dialog=document.createElement('dialog');dialog.id='welcome-guide';dialog.setAttribute('aria-labelledby','welcome-title');document.body.append(dialog);
 const stage=document.querySelector('.village-stage'),launcher=document.createElement('button');launcher.id='welcome-launcher';launcher.innerHTML='🧭 오늘 뭐 할까?<small>플레이 안내 · 의견 남기기</small>';launcher.onclick=()=>open();stage.append(launcher);
 let seen=false;try{seen=localStorage.getItem(key)==='seen';}catch{}
 function remember(){seen=true;try{localStorage.setItem(key,'seen');}catch{}}
 function shell(title,body){dialog.innerHTML='<div class="welcome-heading"><h2 id="welcome-title">'+title+'</h2><button id="welcome-close" aria-label="안내 닫기">×</button></div>'+body;dialog.querySelector('#welcome-close').onclick=()=>dialog.close();if(!dialog.open)dialog.showModal();dialog.scrollTop=0;}
 function open(){
  remember();const played=data.matches>0,caught=(data.nature?.fish?.length||0)+(data.nature?.butterfly?.length||0)>0,grown=data.flock.some(b=>b.stage>0);
  shell('작은 달걀과 놀고, 모으고, 자라요!',`<p class="welcome-lead">동글동글은 <b>달걀을 키우는 마을 + 밀어내기 경기 + 느긋한 탐험</b> 게임이에요. 처음엔 경기 한 판부터 해 보세요!</p><div class="welcome-paths"><article><span>⚑</span><small>${played?'✓ 첫 경기 완료':'추천 · 먼저 해보기'}</small><h3>1. 밀어내기 한 판</h3><p>AI 친구 5마리를 밀어 떨어뜨려요.<br>90초 경기 · 등수에 따라 별조각 획득</p><button data-lesson="battle">경기 방법 보고 시작 →</button></article><article><span>🦋</span><small>${caught?'✓ 첫 생물 발견':'산책하고 싶다면'}</small><h3>2. 마을 탐험하기</h3><p>낚시·나비 잡기·별꽃 찾기!<br>재료를 모아 내 마을에 둥지를 만들어요.</p><button data-lesson="explore">탐험 방법 보고 출발 →</button></article><article><span>🐣</span><small>${grown?'✓ 첫 진화 완료':'친구를 더 만나고 싶다면'}</small><h3>3. 모으고 성장시키기</h3><p>별조각으로 알을 뽑고 진화시켜요.<br>알 → 병아리 → 저마다 다른 새!</p><button data-lesson="grow">성장 방법 보기 →</button></article></div><p class="welcome-note">혼자 즐기는 게임이에요. 저장은 <b>지금 브라우저</b>에 돼요. 기기를 바꿀 때는 ‘마을 관리’에서 저장 파일을 내보내세요.</p><div class="welcome-footer"><button id="welcome-skip">자유롭게 둘러볼래요</button><button id="welcome-feedback">의견 남기기</button><button id="welcome-share">게임 링크 복사</button></div><p id="welcome-status" role="status"></p>`);
  dialog.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>lesson(b.dataset.lesson));dialog.querySelector('#welcome-skip').onclick=()=>dialog.close();dialog.querySelector('#welcome-feedback').onclick=feedback;dialog.querySelector('#welcome-share').onclick=()=>copy('https://egg.thusfar.cloud/');
 }
 async function copy(text){const status=dialog.querySelector('#welcome-status');try{await navigator.clipboard.writeText(text);status.textContent='복사했어요! 링크를 보내 준 사람이나 친구에게 붙여 넣어 주세요.';}catch{status.textContent='자동 복사가 안 돼요. 아래 내용을 선택해서 복사해 주세요.';let box=dialog.querySelector('#welcome-copy');if(!box){box=document.createElement('textarea');box.id='welcome-copy';box.readOnly=true;box.setAttribute('aria-label','복사할 내용');dialog.append(box);}box.value=text;box.focus();box.select();}}
 function lesson(kind){const content={
  battle:['⚑ 밀어내기 첫걸음','① 경기장에서 <b>한 판 시작하기</b>를 눌러요.<br>② 방향키 / WASD로 움직이고 <b>Space</b>로 스킬! 3초마다 다시 쓸 수 있어요.<br>③ 가장자리를 피하며 친구를 바깥으로 밀어요.','휴대폰은 가로로! 왼쪽 조이스틱으로 이동하고 오른쪽 스킬 버튼을 눌러요. 먼저 떨어져도 ‘건너뛰기’로 바로 결과를 볼 수 있어요.','경기장 가기',onBattle],
  explore:['🗺 탐험 첫걸음','① 놀러 갈 마을을 골라요.<br>② <b>나비 찾기 · 낚시터 · 별꽃</b>을 누르면 미니맵에 목적지가 표시돼요.<br>③ 방향키 / WASD로 이동하고, 가까이에서 <b>F</b>로 놀이를 시작해요. 별꽃은 <b>E</b>로 주워요.','나비: 방향키로 조준 → Space로 휘두르기. 낚시: 입질에 Space → 누르고 떼며 장력 조절. 휴대폰은 화면의 조이스틱과 버튼을 사용해요.','마을 골라 출발',onExplore],
  grow:['🐣 내 친구와 오래오래','① <b>내 달걀</b>에서 함께할 친구를 선택해요.<br>② 경기·탐험으로 모은 별조각으로 <b>달걀 뽑기</b>나 진화를 해요.<br>③ <b>둥지·도감</b>에서 조개·꽃잎·가지로 둥지를 만들고 돌보면 새로운 알이 찾아와요.','진화는 직접 선택해요. 한 번 진화하면 이전 모습으로 돌아가지 않아요. ‘마을 꾸미기’에서는 집과 친구를 옮길 수도 있어요.','내 달걀 만나기',onCollection]
 }[kind];shell(content[0],`<div class="welcome-lesson"><p>${content[1]}</p><aside>${content[2]}</aside></div><div class="welcome-footer"><button id="welcome-back">전체 안내</button><button id="welcome-go">${content[3]} →</button></div>`);dialog.querySelector('#welcome-back').onclick=open;dialog.querySelector('#welcome-go').onclick=()=>{dialog.close();content[4]();};}
 function feedback(){shell('💬 해보고 어땠나요?', '<p class="welcome-lead">좋았던 점이나 막혔던 곳을 알려 주세요. <b>복사한 의견을 링크를 보내 준 사람에게 전달</b>하면 돼요. 자동 전송되지는 않아요.</p><label class="welcome-label">가장 해본 것은?<select id="feedback-activity"><option>밀어내기 경기</option><option>탐험·낚시·나비</option><option>뽑기·진화·둥지</option><option>처음 화면만 봤어요</option></select></label><label class="welcome-label">재미는 어땠나요?<select id="feedback-rating"><option>재미있었어요</option><option>조금 더 해보고 싶어요</option><option>뭘 해야 할지 어려웠어요</option><option>개선이 필요해요</option></select></label><label class="welcome-label">좋았던 점 / 헷갈린 점 / 오류<textarea id="feedback-text" maxlength="2000" placeholder="예: 낚시할 때 언제 버튼을 놓아야 할지 헷갈렸어요."></textarea></label><div class="welcome-footer"><button id="welcome-back">전체 안내</button><button id="feedback-copy">의견 복사하기</button></div><p id="welcome-status" role="status"></p>');dialog.querySelector('#welcome-back').onclick=open;dialog.querySelector('#feedback-copy').onclick=()=>copy('[동글동글 플레이 피드백]\n해본 것: '+dialog.querySelector('#feedback-activity').value+'\n느낌: '+dialog.querySelector('#feedback-rating').value+'\n의견: '+dialog.querySelector('#feedback-text').value+'\n화면: '+innerWidth+' × '+innerHeight);}
 dialog.addEventListener('close',remember);
 document.querySelector('#help').addEventListener('click',e=>{if(document.querySelector('#village-page').hidden)return;e.preventDefault();e.stopImmediatePropagation();open();},true);
 setTimeout(()=>{if(!seen&&data.matches===0&&!document.querySelector('dialog[open]')&&!document.querySelector('#village-page').hidden)open();},350);
 return {open};
}
